//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UppdateDatabaseWithVisualStudio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public int EducationId { get; set; }
        public string EducationName { get; set; }
        public Nullable<MyPaymentMethod> PaymentMethod { get; set; }
    }
}
